package ge.mziuri.eventmx.model.command;

public enum Command {
    ADD_EVENT,
    REMOVE_EVENT,
    MAKE_EVENT_PUBLIC,
    CHANGE_EVENT_CAPACITY,
    CHANGE_EVENT_LOCATION,
    RENAME_EVENT,
    ADD_PERSON,
    REMOVE_PERSON,
    SORT_EVENTS_BY_ALPHABET,
    SORT_EVENTS_BY_CAPACITY,
    SORT_EVENTS_BY_DATE
}
